% mainscript for rendering coulomb output
%

clear all
global ha1 ha2 % handle of figure
global x y z cl sigs sign xmin xmax xinc nxinc ymin ymax yinc nyinc
global cmin cmax cmean cc


N = 1; % default number of color saturation stress value
%% ha1 = 0; % initial default value
ha2 = 0; % initial default value
% ns = 1; % default

%% if ha1==0
ha1 = figure('Name','Coulomb rendering',...
    'NumberTitle','off',...
    'Position',[100,300,330,100]);  %left, bottom width height
%%end

% Start button
%% figure(ha1);
%% hold on
PBOpen1 = uicontrol(gcf,...
    'Style','Pushbutton',...
    'Position',[20 50 80 20],...
    'String','Open Coulomb',...
    'Callback',...
    ['coulomb_button(''Open1'',N)']...
    );

PBOpen1 = uicontrol(gcf,...
    'Style','Pushbutton',...
    'Position',[110 50 80 20],...
    'String','Open Input',...
    'Callback',...
    ['coulomb_button(''Open2'',N)']...
    );


% Modifiy button
%{
PBGo = uicontrol(gcf,...
    'Style','Pushbutton',...
    'Position',[90 50 50 20],...
    'String','Go',...
    'Callback',...
    ['coulomb_button(''Go'',2,N)']...
    );
%}

% Exit button
PBExit = uicontrol(gcf,...
    'Style','Pushbutton',...
    'Position',[200 50 50 20],...
    'String','Exit',...
    'Callback',...
    ['coulomb_button(''Exit'',N)']...
    );

% Text edit field (value for color saturation)
EDColor = uicontrol(gcf,...
    'BackGroundColor','w',...
    'Style','edit',...
    'String','5',...
    'Position',[280 20 20 20],...
    'CallBack','N=str2num(get(EDColor,''String''))'...
    );

% Slider
SDbar = uicontrol(gcf,...
    'Style','Slider',...
    'Position',[150 20 100 20],...
    'Min',0,'Max',10,'Value',5,...
    'Callback',...
    'SDbar=get(SDbar,''Value'');coulomb_view(SDbar);set(SDbar,''Value'',SDbar)'...
    );

% Text next the text field
% want to change "system background color"
txt1 = uicontrol(gcf,...
     'BackGroundColor','default',...
    'Style','Text',...
    'String','Saturation',...
    'Position',[20 20 80 10],...
    'HorizontalAlignment','left'...
    );
%% hold off


