hlist = strvcat('input',...   
'input menu',... 
'functions',... 
'functions menu',... 
'overlay',... 
'overlay menu',... 
'about coulomb pc',... 
'open existing input file',... 
'open & edit input file',... 
'build input file from coords',... 
'build input file from map',... 
'save input file as ascii',... 
'save input+overlays as binary',... 
'add coords to input file',... 
'preferences',... 
'grid',... 
'2d map view',... 
'3d view',... 
'displacements',... 
'horizontal displ. (vectors)',... 
'vertical displ.',... 
'3d image drape',... 
'3d wireframed surface',... 
'strain',... 
'stress',... 
'shear stress change',... 
'normal stress change',... 
'coulomb stress change',... 
'calc. stress on faults',... 
'calc. stress on a point',... 
'calc. stress on nodal plane',... 
'change parameters',... 
'all input parameters',... 
'grid size',... 
'calculation depth',... 
'coeff. friction',... 
'vertical exaggeration',... 
'tools',...
'quit coulomb',...
'lauch coulomb',...
'input file (open)',...
'horizontal displ. (wireframe)',...
'friction',...
'regional stress',...
'poisson ratio',...
'young modulus',...
'source fault',...
'receiver fault',...
'opt. faults',...
'opt. strike-slip faults',...
'opt. thrust faults',...
'opt. normal faults',...
'specified fault',...
'strike line',...
'strike',...
'dip',...
'rake',...
'aki and richards convention',...
'plug-ins',...
'coulomb2googleearth',...
'digitize_polygon',...
'kode',...
'unit',...
'taper',...
'subdivide',...
'principal axes calculator',...
'gps stations',...
'annotations',...
'earthquake plot',...
'active fault plot',...
'coastline plot',...
'global cmt',...
'japan meteorological agency (JMA)',...
'southern california eq center',...
'northern california eq center',...
'usgs neic screen format',...
'zmap formatted catalog',...
'nied f-net catalog',...
'nied hi-net auto catalog',...
'kandilli turkey catalog',...
'hypodd/tomodd',...
'northern california dd',...
'sousus',...
'input file building');
